export default {
    NON_TECH_EVENTS_LOADING: 'NON_TECH_EVENTS_LOADING',
    REGISTER_GAMING_EVENT_SUCCESS: 'REGISTER_GAMING_EVENT_SUCCESS',
    REGISTER_DREAM11IPL_EVENT_SUCCESS: 'REGISTER_DREAM11IPL_EVENT_SUCCESS',
    REGISTER_TREASUREHUNT_EVENT_SUCCESS: 'REGISTER_TREASUREHUNT_EVENT_SUCCESS',
    REGISTER_CONNEXIONS_EVENT_SUCCESS: 'REGISTER_CONNEXIONS_EVENT_SUCCESS',
    REGISTER_DUBSMASH_EVENT_SUCCESS: 'REGISTER_DUBSMASH_EVENT_SUCCESS',
    REGISTER_GAMING_EVENT_FAIL: 'REGISTER_GAMING_EVENT_FAIL',
    REGISTER_DREAM11IPL_EVENT_FAIL: 'REGISTER_DREAM11IPL_EVENT_FAIL',
    REGISTER_TREASUREHUNT_EVENT_FAIL: 'REGISTER_TREASUREHUNT_EVENT_FAIL',
    REGISTER_CONNEXIONS_EVENT_FAIL: 'REGISTER_CONNEXIONS_EVENT_FAIL',
    REGISTER_DUBSMASH_EVENT_FAIL: 'REGISTER_DUBSMASH_EVENT_FAIL',
}
