export default {
    TECH_EVENTS_LOADING: 'TECH_EVENTS_LOADING',
    REGISTER_CODING_EVENT_SUCCESS: 'REGISTER_CODING_EVENT_SUCCESS',
    REGISTER_PAPERPRESENTATION_EVENT_SUCCESS:
        'REGISTER_PAPERPRESENTATION_EVENT_SUCCESS',
    REGISTER_DEBUGGING_EVENT_SUCCESS: 'REGISTER_DEBUGGING_EVENT_SUCCESS',
    REGISTER_HACKATHON_EVENT_SUCCESS: 'REGISTER_HACKATHON_EVENT_SUCCESS',
    REGISTER_CODING_EVENT_FAIL: 'REGISTER_CODING_EVENT_FAIL',
    REGISTER_PAPERPRESENTATION_EVENT_FAIL:
        'REGISTER_PAPERPRESENTATION_EVENT_FAIL',
    REGISTER_DEBUGGING_EVENT_FAIL: 'REGISTER_DEBUGGING_EVENT_FAIL',
    REGISTER_HACKATHON_EVENT_FAIL: 'REGISTER_HACKATHON_EVENT_FAIL',
}
